### PR TITLE
Fix ansi-regex cve issue-305

### PR DESCRIPTION
**Pull request by Rishi-web**
w.r.t issue 
https://github.ibm.com/kms/psirt-issue-tracker/issues/305
some of the related packages are updated to latest version to fix ansi-regex vulnerability issue.

### CODE REVIEW

**Comment by Rishi-web** [comment]
Test result

Screenshot 2022-08-04 at 5 30 57 PM

**Comment by thu2thu2** [comment]
Looks good to me.

**Comment by Rishi-web** [comment]
As of now `pretty-format` is using `ans-regex -5.0.0` with `caret(^)` symbol, which internally downloads the stable version.
Screenshot 2022-08-08 at 11 24 01 AM

**Comment by Rishi-web** [comment]
The final `ansi-regex` which gets download after doing `npm install` is 5.0.1 which is free from any vulnerabilities. 
w.r.t - https://security.snyk.io/package/npm/ansi-regex

Screenshot 2022-08-08 at 11 32 46 AM

**Comment by Rishi-web** [comment]
No more - `ansi-regex-5.0.0.tgz` in nodejs-client code base

Screenshot 2022-08-08 at 11 24 27 AM

**Pull request merged**
